### ISSUE TITLE
Everything breaks on mobile

### ISSUE THREAD

**Issue by ErikBoesen** [FCCPSTSA/MEH-Web-Design-2015#15]

**Comment by pauloca** [comment]
Dude jam is on that. also, are they even gonna test it on mobile?

**Comment by ErikBoesen** [comment]
Yes, that's an important part of the scoring.

**Comment by jamestrombo** [comment]
Oh lol

**Comment by pauloca** [comment]
wait really

**Comment by ErikBoesen** [comment]
Yeah.

**Comment by ErikBoesen** [comment]
Hold on, apparently it's not very important for Middle School, just High school.
