### ISSUE TITLE
Background images are way too high resolution

### ISSUE THREAD

**Issue by ErikBoesen** [FCCPSTSA/MEH-Web-Design-2015#16]
Creates lag and burns bandwidth. To fix, just scale images down.

**Comment by pauloca** [comment]
there is no noticeable amount of lag  that i've noticed when testing it that anything will fix.

**Comment by ErikBoesen** [comment]
Since you have it stored locally on your computer, it will load quicker. It lags a lot for me. And you should reduce the data that needs to be loaded anyway.

**Comment by pauloca** [comment]
Tested the load time, it's under 0.5 seconds, even with scaling the images. And this is on the web-hosted site.

**Comment by ErikBoesen** [comment]
So did you scale the images down?

**Comment by pauloca** [comment]
I tried it. I reverted again. it doesn't matter.

**Comment by ErikBoesen** [comment]
Please don't. It really does make a difference, especially for mobile users who don't want to waste their data.

**Comment by jamestrombo** [comment]
Erik, I know a way to convince paulo, call him daddy

**Comment by ErikBoesen** [comment]
I'm almost three years older than both of you

**Comment by jamestrombo** [comment]
Yeah almost three years, if you forget about a year. Must be lupus

**Comment by ErikBoesen** [comment]
I said almost, not three whole years

**Comment by pauloca** [comment]
When's your birthday?

**Comment by pauloca** [comment]
btw erik lets work on codeon after this whole thing is over

**Comment by ErikBoesen** [comment]
October 9 2k

And yes, yes

**Comment by ErikBoesen** [comment]
effin thanxs

**Comment by jamestrombo** [comment]
BIG DADDY
