### ISSUE TITLE
Scaling animation on history timeline needs work

### ISSUE THREAD

**Issue by ErikBoesen** [FCCPSTSA/MEH-Web-Design-2015#17]

**Comment by pauloca** [comment]
we can't fix that
die

**Comment by jamestrombo** [comment]
Real talk tho how would we fix it

**Comment by ErikBoesen** [comment]
My recommendation: make it start as a point, then scale out in both directions, then open down (or up if it's on top).

**Comment by pauloca** [comment]
Dude we can't
its not how it's coded

**Comment by pauloca** [comment]
I'll recode it if you want but that's just not really worth it.

**Comment by ErikBoesen** [comment]
codepen.io/ErikBoesen/pen/vGPXeZ

**Comment by pauloca** [comment]
it's kinda work
best i can do before the competition
