### ISSUE TITLE
Fade timeline boxes in and out

### ISSUE THREAD

**Issue by ErikBoesen** [FCCPSTSA/MEH-Web-Design-2015#4]

**Comment by pauloca** [comment]
I made them resize. It's good enough.

**Comment by ErikBoesen** [comment]
That works too. Just some transition.

**Comment by jamestrombo** [comment]
Well I made them resize, you just made it pretty

**Comment by pauloca** [comment]
Nah, they didn't resize right before.

**Comment by jamestrombo** [comment]
Well right...
